import {
  BLS12_381_SCALAR_FIELD,
  addMod,
  fieldHash,
  mimcFeistel,
  mulMod,
  randomField,
} from "./field.util";

describe("mimcFeistel", () => {
  it("matches the on-chain circuit's reference vector exactly", () => {
    // Generated by compiling circuits/payment-proof/payment_proof.circom and
    // running the real Groth16 witness/proof pipeline for these exact inputs
    // - this proof was independently submitted to and verified true by the
    // deployed Stellar testnet contract (CAO2EEH75TIJWGQEMKIO2RLDPWHQJ7HLDTG7HVYYGS6ZEV62HZQYDGSW).
    // If this test ever fails, the backend's commitment no longer matches
    // what the circuit/contract actually verify.
    const requestId = 12345n;
    const listingId = 9876n;
    const fee = 10n;
    const commitment = addMod(
      mimcFeistel(111n, 222n),
      mulMod(requestId, listingId),
      fee,
    );
    expect(commitment.toString()).toBe(
      "36641870119524741684872236590800899687401000478095830012568547819568772422937",
    );
  });

  it("is deterministic for the same inputs", () => {
    const a = mimcFeistel(111n, 222n);
    const b = mimcFeistel(111n, 222n);
    expect(a).toBe(b);
  });

  it("produces different output when the secret changes", () => {
    const a = mimcFeistel(111n, 222n);
    const b = mimcFeistel(112n, 222n);
    expect(a).not.toBe(b);
  });

  it("produces different output when the nonce changes", () => {
    const a = mimcFeistel(111n, 222n);
    const b = mimcFeistel(111n, 223n);
    expect(a).not.toBe(b);
  });

  it("is not symmetric in its two inputs (left and right play different roles)", () => {
    const a = mimcFeistel(111n, 222n);
    const b = mimcFeistel(222n, 111n);
    expect(a).not.toBe(b);
  });

  it("always returns a value within the BLS12-381 scalar field", () => {
    const out = mimcFeistel(123456789n, 987654321n);
    expect(out).toBeGreaterThanOrEqual(0n);
    expect(out).toBeLessThan(BLS12_381_SCALAR_FIELD);
  });

  it("is not invertible by the trivial relation it replaced (no small-collision shortcut)", () => {
    // The previous "secret^2 + nonce^2" relation let anyone solve for an
    // alternate (secret, nonce) pair via a modular square root. Sanity
    // check there's no equally trivial relationship for MiMCFeistel: a
    // handful of small (secret, nonce) pairs should not collide.
    const seen = new Set<string>();
    for (let s = 0n; s < 20n; s++) {
      for (let n = 0n; n < 20n; n++) {
        const out = mimcFeistel(s, n).toString();
        expect(seen.has(out)).toBe(false);
        seen.add(out);
      }
    }
  });
});

describe("fieldHash", () => {
  it("is deterministic for the same input", () => {
    expect(fieldHash("abc")).toBe(fieldHash("abc"));
  });

  it("produces different output for different input", () => {
    expect(fieldHash("abc")).not.toBe(fieldHash("abd"));
  });

  it("stays within the scalar field", () => {
    expect(fieldHash("anything")).toBeLessThan(BLS12_381_SCALAR_FIELD);
  });
});

describe("randomField", () => {
  it("stays within the scalar field", () => {
    for (let i = 0; i < 20; i++) {
      expect(randomField()).toBeLessThan(BLS12_381_SCALAR_FIELD);
    }
  });

  it("is not constant across calls", () => {
    const values = new Set(
      Array.from({ length: 10 }, () => randomField().toString()),
    );
    expect(values.size).toBeGreaterThan(1);
  });
});

describe("mulMod / addMod", () => {
  it("reduce modulo the BLS12-381 scalar field", () => {
    const big = BLS12_381_SCALAR_FIELD - 1n;
    expect(mulMod(big, 2n)).toBe((big * 2n) % BLS12_381_SCALAR_FIELD);
    expect(addMod(big, 5n)).toBe((big + 5n) % BLS12_381_SCALAR_FIELD);
  });

  it("addMod sums an arbitrary number of values", () => {
    expect(addMod(1n, 2n, 3n, 4n)).toBe(10n);
  });
});
